spring:
  application:
    name: hospital-queue-system

  security:
    user:
      name: admin
      password: admin

    jwt:
      secret: HOSPITAL_QUEUE_9F3A2B8D7C1E5A6F9D3C2B1A
      expiration: 86400000 # 24 hours

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_queue_db?useSSL=false&serverTimezone=UTC
    username: root
    password: sdlove01
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8081

ml:
  service:
    url: http://localhost:5000

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
